env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"

task:
  name: Test, build and upload
  timeout_in: 240m
    container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
  env_script: env
  show_script: cat $CIRRUS_WORKING_DIR/build_rom.sh
  notify_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/notify.sh | bash
  test_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/test.sh | bash
  test_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/test.sh | bash
  sync_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/sync.sh | bash
  tsync_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/tsync.sh | bash
  build_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/build.sh | bash
  ccache_stats_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/ccache_stats.sh | bash
  upload_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/upload.sh | bash
  remove_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/remove.sh | bash
  test_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/test.sh | bash
  post_build_script: curl -Ls https://raw.githubusercontent.com/ROM-builders/temporary/main/ci/post_build.sh | bash
